In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Adam", "Eve", "Bob"],
    "Marks" : [78, 99, 85],
    "Grade" : ['B', 'O', 'A']
}
df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Grade'], dtype='object')

In [3]:
df

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A

In [4]:
# DataFrom using Numpy array
import numpy as np
np_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(np_arr, columns=["Col1", "Col2", "Col3"])
print(df)

   Col1  Col2  Col3
0     1     2     3
1     4     5     6
2     7     8     9

In [5]:
# DataFrom using Lists
list = [["Adam", 96], ["Eve", 75], ["Bob", 82], ["Charlie", 92]]
df = pd.DataFrame(list, columns=["Name", "Marks"])
print(df)

      Name  Marks
0     Adam     96
1      Eve     75
2      Bob     82
3  Charlie     92

In [6]:
# Read csv data
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [7]:
# Read json data
df = pd.read_json("employee_data.json")
# print(df, type(df))

# For excel => read_excel
# For sql => read_sql

In [8]:
# DataFrame Methods

df.head() # showed starting 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [9]:
df.tail() #showed ending 5 rows
df.tail(2) #showed endding 2 rows

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [10]:
df.sample() #showed a random row
df.sample(2) #showed 2 random rows

   ID   Name  Age Department  Salary
5   6  Frank   29    Finance   50000
9  10  Julia   30    Finance   60000

In [11]:
df.info() #showed information about data table

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [12]:
df.shape #showed dataFrame shape in tuple

(10, 5)

In [13]:
df.describe() #Describe numerical computation of the table

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [14]:
df.columns #showed all columns name of the table

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [15]:
df.nunique() # showed total number of unique rows

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [16]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000