In [1]:
import pandas as pd

In [2]:
# Data cleaning
df = pd.read_csv("raw_data.csv")

In [3]:
# Data Transformation: Feature Engineering

df2 = df.copy()
# add new column
df2["tax"] = df2["income"].apply(lambda x: "20%" if x >= 60_000 else "10%")

# maping
gender_map = {"Male":"M", "Female" : "F", "Unknown": "U"}
df2["gender"] = df2["gender"].map(gender_map)

# assign function
df2 = df2.assign(new_income = df2["income"] * 1.1)

# replace(old, new) function
df2["country"] = df2["country"].replace("USA", "US")

# rename
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"]
df2 = df2.rename(columns={"Income": "Salary"})
df2 = df2.rename(index={"first": 0})

# Sorting - values & index
df2["Age"] = df2["Age"].fillna(50)
df2.sort_values("Salary")
# df2.sort_values("Salary", ascending = False)
sorted_df2 = df2.sort_values(["Salary", "Age"])

sorted_df2.sort_index()

# reset index
sorted_df2.reset_index()
sorted_df2.reset_index(drop = True)

# Ranking
sorted_df2["Ranking"] = sorted_df2["Salary"].rank()
sorted_df2["Ranking"] = sorted_df2["Salary"].rank(ascending= False, method = "max") # dense, min

sorted_df2[["Id", "Name", "Age", "Country", "Gender", "Salary", "New_Income", "Ranking", "Tax"]]

    Id          Name   Age Country Gender   Salary  New_Income  Ranking  Tax
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0     49500.0     10.0  10%
3    3          Alex  50.0      US      U  47000.0     51700.0      9.0  10%
5    5        Li Wei  27.0   China      M  51000.0     56100.0      8.0  10%
0    1      John Doe  29.0      US      M  55000.0     60500.0      7.0  10%
1    1      John Doe  29.0      US      M  55000.0     60500.0      7.0  10%
10  10   Emily Davis  31.0      US    NaN  58000.0     63800.0      5.0  10%
8    8    Rachel Lee  29.0      US      F  62000.0     68200.0      4.0  20%
2    2    Jane Smith  50.0  Canada      F  62000.0     68200.0      4.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0     74800.0      2.0  20%
6    6           NaN  45.0   India      F  73000.0     80300.0      1.0  20%
4    4  Maria Garcia  34.0   Spain      F      NaN         NaN      NaN  10%

In [4]:
# Practice Task
# set new col order using list comperhension
df3 = df.copy()
new_col_order = [col for col in df3.columns if col != "id"] + ["id"]
df3 = df3[new_col_order]
df3.columns = df3.columns.str.capitalize()
df3

            Name   Age Country   Gender   Income  Id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [7]:
# Grouping and Aggregation

df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

df.groupby("gender")["income"].mean()
df.groupby("gender")["age"].min()

# Aggregation
df.groupby("country")["income"].agg(["mean", "min", "max"])
df.groupby("country")["income"].aggregate(["mean", "min", "max"])

df.groupby("country")["income"].agg(avg_income="mean", min_income="min", max_income="max")

df.groupby("country").agg({
    "income" : "mean",
    "age" : "min"
})
df.groupby("country").agg(
    avg_income=("income", "mean"),
    min_age=("age" , "min")
)

         avg_income  min_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         55400.0     29.0

In [6]:
# Melt and Pivot for Reshaping
# Melting
df4 = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22]
})

melted_df = df4.melt(
    id_vars=["country", "year"],     # columns to keep
    value_vars=["sales", "profit"],  # columns to unpivot or melting
    var_name="metric",               # new column name for variable
    value_name="value (in Lakhs)"    # new column name for value (default is value)
)
melted_df

# Pivoting
original_df = melted_df.pivot(
    index=["country", "year"],   # cols that become the NEW row index - can't for just country
    columns="metric",            # col whose unique values will become the cols
    values="value (in Lakhs)"    # col whose values will fill the new df
)
original_df

metric        profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120